version: "3"
services:
  postgres:
    ports:
    - "5432:5432"
  otel-agent:
    ports:
      - "4317:4317" # OpenTelemetry receiver
  bitcoind:
    ports:
      - "18443:18443"
  bitcoind-signer:
    ports:
      - "18543:18443"
  lnd:
    ports:
      - "10009:10009"
  fulcrum:
    ports:
      - "50001:50001"
      - "50002:50002"
  mempool:
    ports:
      - "8999:8999"
      
  
