name: "E2E Tests"

on:
  pull_request:
    branches: [main]

jobs:
  integration:
    name: End to End Test
    runs-on: ubuntu-latest
    steps:
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4
      - name: Run the Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v2
      - uses: actions/checkout@v3
      - name: Run e2e tests
        env:
          PG_CON: postgres://user:password@127.0.0.1:5432/pg
        run: nix develop -c make e2e
